spring.application.name=bkedInventario

server.port = 8862

spring.datasource.url=${nombre_bd}
spring.datasource.username=${usuario_bd}
spring.datasource.password=${clave_bd}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

